# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='year_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='semester',
            name='sem_type',
            field=models.CharField(choices=[('l', 'letni'), ('z', 'zimowy')], default='z', max_length=1),
        ),
    ]
