# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160905_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
