# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_semester_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
